"use client";

import { useSyncExternalStore } from "react";
import { useTranslate } from "@tolgee/react";

export type AppLanguage = "en" | "hi" | "kn" | "te" | "ta" | "ml";

export const appLanguages: { code: AppLanguage; label: string }[] = [
  { code: "en", label: "English" },
  { code: "hi", label: "Hindi" },
  { code: "kn", label: "Kannada" },
  { code: "te", label: "Telugu" },
  { code: "ta", label: "Tamil" },
  { code: "ml", label: "Malayalam" },
];

const languageKey = "rvk:language";

const legacyLanguageMap: Record<string, AppLanguage> = {
  English: "en",
  Hindi: "hi",
  Kannada: "kn",
  Telugu: "te",
  Tamil: "ta",
  Malayalam: "ml",
};

function normalizeLanguage(value: string | null): AppLanguage {
  if (!value) return "en";
  if (value in legacyLanguageMap) return legacyLanguageMap[value];
  return appLanguages.some((item) => item.code === value) ? (value as AppLanguage) : "en";
}

function getLanguageSnapshot(): AppLanguage {
  if (typeof window === "undefined") return "en";
  return normalizeLanguage(localStorage.getItem(languageKey));
}

function getServerLanguageSnapshot(): AppLanguage {
  return "en";
}

function subscribeLanguage(callback: () => void) {
  window.addEventListener("rvk:language-change", callback);
  window.addEventListener("storage", callback);

  return () => {
    window.removeEventListener("rvk:language-change", callback);
    window.removeEventListener("storage", callback);
  };
}

export function applyLanguage(nextLanguage: AppLanguage) {
  if (typeof window === "undefined") return;
  localStorage.setItem(languageKey, nextLanguage);
  window.dispatchEvent(new Event("rvk:language-change"));
}

export function useLanguage() {
  return useSyncExternalStore(subscribeLanguage, getLanguageSnapshot, getServerLanguageSnapshot);
}

type TranslationKey = string;

type TranslationMap = Record<TranslationKey, string>;

export const localTranslations: Record<AppLanguage, TranslationMap> = {
  en: {
    accountAndPreferences: "Account and preferences",
    accountDetails: "Account details",
    analyzeData: "Analyze Data",
    analyzeImage: "Analyze Image",
    archive: "Archive",
    archived: "Archived",
    attach: "Attach",
    brainstorm: "Brainstorm",
    camera: "Camera",
    closeProfile: "Close profile",
    copied: "Copied",
    copy: "Copy",
    current: "Current",
    dark: "Dark",
    delete: "Delete",
    document: "Document",
    email: "Email",
    emailUpdated: "Email updated.",
    generateIdeas: "Generate Ideas",
    generateImages: "Generate Images",
    helpMeWrite: "Help me write",
    improveWriting: "Improve writing",
    language: "Language",
    learnAbout: "Learn about",
    light: "Light",
    logout: "Logout",
    messagePlaceholder: "Message RVK",
    microphoneDenied: "Microphone permission was denied.",
    myProfile: "My profile",
    name: "Name",
    nameUpdated: "Name updated.",
    newChat: "New chat",
    preferences: "Preferences",
    preferencesDescription: "Adjust the interface for your workspace.",
    profileDescription: "Keep your display name and sign-in email up to date.",
    photos: "Photos",
    recents: "Recents",
    rename: "Rename",
    searchChats: "Search chats",
    seeLess: "See less",
    seeMore: "See more",
    sendMessage: "Send message",
    startVoiceInput: "Start voice input",
    stopVoiceInput: "Stop voice input",
    voiceInputStopped: "Voice input stopped.",
    summarizeText: "Summarize text",
    switchToDark: "Switch to dark mode",
    switchToLight: "Switch to light mode",
    theme: "Theme",
    translate: "Translate",
    unarchive: "Unarchive",
    unpin: "Unpin",
    update: "Update",
    updating: "Updating",
    user: "User",
    voiceUnsupported: "Voice input is not supported",
    listeningMessage: "Listening... speak naturally, then tap the mic to stop.",
    welcomeDescription: "Ask anything, attach files, or continue from a saved thread.",
    welcomeTitle: "What are we working on?",
    alreadyHaveAccount: "Already have an account?",
    archivedChats: "Archived chats",
    answeredWith: "Answered with",
    attachFile: "Attach file",
    attachmentTooLarge: "is larger than the 12 MB attachment limit.",
    backToSignIn: "Back to sign in",
    cameraPhoto: "Camera photo",
    checkCredentials: "Check your email and password, then try again.",
    chooseNewPassword: "Choose a new password",
    confirmNewPassword: "Confirm new password",
    confirmPassword: "Confirm password",
    continueToChat: "Continue to chat",
    continueWithGithub: "Continue with GitHub",
    continueWithGoogle: "Continue with Google",
    couldNotAttachFile: "Could not attach that file.",
    couldNotSendResetLink: "Could not send reset link.",
    couldNotStartVoiceInput: "Could not start voice input.",
    createAccount: "Create account",
    createAccountTitle: "Create your account",
    creatingAccount: "Creating account",
    collapseSidebar: "Collapse sidebar",
    emailAddress: "Email address",
    enterEmailAddress: "Enter your email address.",
    expandSidebar: "Expand sidebar",
    fillAllFields: "Fill in all fields to continue.",
    forgotPassword: "Forgot password?",
    forgotPasswordDescription: "Enter your account email and we will send a reset link if the account exists.",
    fullName: "Full name",
    homeFeatureModelDescription: "Use Gemini or LLaMA from one clean composer.",
    homeFeatureModelTitle: "Model choice",
    homeFeatureSavedDescription: "Find, rename, archive, and revisit conversations.",
    homeFeatureSavedTitle: "Saved threads",
    homeFeatureSecureDescription: "Your chats stay tied to your account.",
    homeFeatureSecureTitle: "Secure sessions",
    homeHeroDescription: "Start chats quickly, switch between Gemini and LLaMA models, and keep your conversation history organized in one responsive interface.",
    homeHeroTitle: "A cleaner workspace for focused AI conversations.",
    ifAccountExistsResetSent: "If an account exists, a reset link has been sent.",
    makePasswordDescription: "Make it memorable, private, and at least 6 characters.",
    missingResetToken: "This reset link is missing a token.",
    newHere: "New here?",
    newPassword: "New password",
    noResponseFromAi: "No response from AI",
    noEmailAvailable: "No email available",
    onboardingDescription: "Start a new chat, pick a model, and keep useful conversations organized in the sidebar.",
    onboardingTitle: "Your workspace is ready",
    or: "OR",
    password: "Password",
    passwordLengthGood: "Password length looks good.",
    passwordMinLength: "Use at least 6 characters.",
    passwordMinLengthNew: "Use at least 6 characters for your new password.",
    passwordsDoNotMatch: "Passwords do not match.",
    passwordResetSuccessful: "Password reset successful. Redirecting to sign in...",
    pin: "Pin",
    analyzeAttachedFile: "Please analyze the attached file.",
    failedToConnectAi: "Failed to connect to AI API",
    fallbackNotice: "Note:",
    fallbackUnavailable: "was unavailable",
    preparingWorkspace: "Preparing workspace",
    recentChats: "Recent chats",
    resetPassword: "Reset password",
    resetPasswordTitle: "Reset your password",
    resettingPassword: "Resetting password",
    removeAttachment: "Remove",
    renameChatPrompt: "Rename chat",
    sendResetLink: "Send reset link",
    sendingLink: "Sending link",
    signIn: "Sign in",
    signInDescription: "Sign in to continue your conversations.",
    signUpDescription: "Save chat history, organize threads, and use multiple models.",
    signingIn: "Signing in",
    signupFailed: "Signup failed.",
    somethingWentWrong: "Something went wrong. Please try again.",
    somethingWentWrongShort: "Something went wrong",
    start: "Start",
    instead: "instead",
    thinking: "Thinking...",
    toggleDarkMode: "Toggle dark mode",
    unableToResetPassword: "Unable to reset password.",
    unableToUpdateProfile: "Unable to update profile.",
    untitledChat: "Untitled chat",
    useSixPassword: "Use at least 6 characters for your password.",
    welcomeBack: "Welcome back",
  },
  hi: {
    accountAndPreferences: "खाता और प्राथमिकताएं",
    accountDetails: "खाता विवरण",
    analyzeData: "डेटा विश्लेषण",
    analyzeImage: "चित्र विश्लेषण",
    archive: "आर्काइव",
    archived: "आर्काइव",
    attach: "जोड़ें",
    brainstorm: "विचार मंथन",
    camera: "कैमरा",
    closeProfile: "प्रोफाइल बंद करें",
    copied: "कॉपी हुआ",
    copy: "कॉपी",
    current: "वर्तमान",
    dark: "डार्क",
    delete: "हटाएं",
    document: "दस्तावेज़",
    email: "ईमेल",
    emailUpdated: "ईमेल अपडेट हुआ।",
    generateIdeas: "विचार बनाएं",
    generateImages: "चित्र बनाएं",
    helpMeWrite: "लिखने में मदद",
    improveWriting: "लेखन सुधारें",
    language: "भाषा",
    learnAbout: "जानें",
    light: "लाइट",
    logout: "लॉगआउट",
    messagePlaceholder: "RVK को संदेश भेजें",
    myProfile: "मेरी प्रोफाइल",
    name: "नाम",
    nameUpdated: "नाम अपडेट हुआ।",
    newChat: "नई चैट",
    preferences: "प्राथमिकताएं",
    preferencesDescription: "अपने कार्यक्षेत्र के लिए इंटरफेस बदलें।",
    profileDescription: "अपना नाम और साइन-इन ईमेल अपडेट रखें।",
    photos: "फोटो",
    recents: "हाल की चैट",
    rename: "नाम बदलें",
    searchChats: "चैट खोजें",
    seeLess: "कम दिखाएं",
    seeMore: "और देखें",
    sendMessage: "संदेश भेजें",
    startVoiceInput: "वॉइस इनपुट शुरू करें",
    stopVoiceInput: "वॉइस इनपुट बंद करें",
    summarizeText: "सारांश बनाएं",
    switchToDark: "डार्क मोड करें",
    switchToLight: "लाइट मोड करें",
    theme: "थीम",
    translate: "अनुवाद",
    unarchive: "आर्काइव हटाएं",
    unpin: "अनपिन",
    update: "अपडेट",
    updating: "अपडेट हो रहा है",
    user: "यूजर",
    voiceUnsupported: "वॉइस इनपुट समर्थित नहीं है",
    listeningMessage: "सुन रहा है... स्वाभाविक रूप से बोलें, फिर रोकने के लिए माइक दबाएं।",
    welcomeDescription: "कुछ भी पूछें, फाइलें जोड़ें, या सेव चैट जारी रखें।",
    welcomeTitle: "आज क्या काम करें?",
    signIn: "साइन इन",
    start: "शुरू करें",
    createAccount: "खाता बनाएं",
    welcomeBack: "वापसी पर स्वागत है",
    signInDescription: "अपनी बातचीत जारी रखने के लिए साइन इन करें।",
    emailAddress: "ईमेल पता",
    password: "पासवर्ड",
    forgotPassword: "पासवर्ड भूल गए?",
    signingIn: "साइन इन हो रहा है",
    or: "या",
    continueWithGoogle: "Google के साथ जारी रखें",
    continueWithGithub: "GitHub के साथ जारी रखें",
    newHere: "नए हैं?",
    homeHeroTitle: "केंद्रित AI बातचीत के लिए साफ़ workspace।",
    homeHeroDescription: "जल्दी चैट शुरू करें, Gemini और LLaMA मॉडल बदलें, और अपनी बातचीत का इतिहास एक responsive interface में व्यवस्थित रखें।",
    homeFeatureSecureTitle: "सुरक्षित सेशन",
    homeFeatureSecureDescription: "आपकी चैट आपके खाते से जुड़ी रहती हैं।",
    homeFeatureModelTitle: "मॉडल चुनाव",
    homeFeatureModelDescription: "एक साफ़ composer से Gemini या LLaMA इस्तेमाल करें।",
    homeFeatureSavedTitle: "सेव किए गए थ्रेड",
    homeFeatureSavedDescription: "बातचीत खोजें, नाम बदलें, आर्काइव करें, और फिर से खोलें।",
  },
  kn: {
    accountAndPreferences: "ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳು",
    accountDetails: "ಖಾತೆ ವಿವರಗಳು",
    analyzeData: "ಡೇಟಾ ವಿಶ್ಲೇಷಿಸಿ",
    analyzeImage: "ಚಿತ್ರ ವಿಶ್ಲೇಷಿಸಿ",
    archive: "ಆರ್ಕೈವ್",
    archived: "ಆರ್ಕೈವ್",
    attach: "ಲಗತ್ತಿಸಿ",
    brainstorm: "ಆಲೋಚನೆ ಮಾಡಿ",
    camera: "ಕ್ಯಾಮೆರಾ",
    closeProfile: "ಪ್ರೊಫೈಲ್ ಮುಚ್ಚಿ",
    copied: "ಕಾಪಿ ಆಯಿತು",
    copy: "ಕಾಪಿ",
    current: "ಪ್ರಸ್ತುತ",
    dark: "ಡಾರ್ಕ್",
    delete: "ಅಳಿಸಿ",
    document: "ಡಾಕ್ಯುಮೆಂಟ್",
    email: "ಇಮೇಲ್",
    emailUpdated: "ಇಮೇಲ್ ಅಪ್ಡೇಟ್ ಆಯಿತು.",
    generateIdeas: "ಆಲೋಚನೆ ರಚಿಸಿ",
    generateImages: "ಚಿತ್ರ ರಚಿಸಿ",
    helpMeWrite: "ಬರೆಯಲು ಸಹಾಯ",
    improveWriting: "ಬರಹ ಸುಧಾರಿಸಿ",
    language: "ಭಾಷೆ",
    learnAbout: "ತಿಳಿಯಿರಿ",
    light: "ಲೈಟ್",
    logout: "ಲಾಗ್ ಔಟ್",
    messagePlaceholder: "RVK ಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ",
    myProfile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    name: "ಹೆಸರು",
    nameUpdated: "ಹೆಸರು ಅಪ್ಡೇಟ್ ಆಯಿತು.",
    newChat: "ಹೊಸ ಚಾಟ್",
    preferences: "ಆದ್ಯತೆಗಳು",
    preferencesDescription: "ನಿಮ್ಮ ಕೆಲಸದ ಸ್ಥಳಕ್ಕೆ ಇಂಟರ್ಫೇಸ್ ಬದಲಿಸಿ.",
    profileDescription: "ನಿಮ್ಮ ಹೆಸರು ಮತ್ತು ಸೈನ್-ಇನ್ ಇಮೇಲ್ ನವೀಕರಿಸಿ.",
    photos: "ಫೋಟೋಗಳು",
    recents: "ಇತ್ತೀಚಿನವು",
    rename: "ಹೆಸರು ಬದಲಿಸಿ",
    searchChats: "ಚಾಟ್ ಹುಡುಕಿ",
    seeLess: "ಕಡಿಮೆ ನೋಡಿ",
    seeMore: "ಇನ್ನಷ್ಟು ನೋಡಿ",
    sendMessage: "ಸಂದೇಶ ಕಳುಹಿಸಿ",
    startVoiceInput: "ಧ್ವನಿ ಇನ್ಪುಟ್ ಆರಂಭಿಸಿ",
    stopVoiceInput: "ಧ್ವನಿ ಇನ್ಪುಟ್ ನಿಲ್ಲಿಸಿ",
    summarizeText: "ಸಾರಾಂಶ ಮಾಡಿ",
    switchToDark: "ಡಾರ್ಕ್ ಮೋಡ್",
    switchToLight: "ಲೈಟ್ ಮೋಡ್",
    theme: "ಥೀಮ್",
    translate: "ಅನುವಾದ",
    unarchive: "ಆರ್ಕೈವ್ ತೆಗೆದುಹಾಕಿ",
    unpin: "ಅನ್ಪಿನ್",
    update: "ಅಪ್ಡೇಟ್",
    updating: "ಅಪ್ಡೇಟ್ ಆಗುತ್ತಿದೆ",
    user: "ಬಳಕೆದಾರ",
    voiceUnsupported: "ಧ್ವನಿ ಇನ್ಪುಟ್ ಬೆಂಬಲಿತವಲ್ಲ",
    listeningMessage: "ಕೇಳುತ್ತಿದೆ... ಸಹಜವಾಗಿ ಮಾತನಾಡಿ, ನಂತರ ನಿಲ್ಲಿಸಲು ಮೈಕ್ ಒತ್ತಿ.",
    welcomeDescription: "ಏನಾದರೂ ಕೇಳಿ, ಫೈಲ್ ಸೇರಿಸಿ, ಅಥವಾ ಉಳಿಸಿದ ಚಾಟ್ ಮುಂದುವರಿಸಿ.",
    welcomeTitle: "ನಾವು ಏನು ಕೆಲಸ ಮಾಡೋಣ?",
    signIn: "ಸೈನ್ ಇನ್",
    start: "ಪ್ರಾರಂಭಿಸಿ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    welcomeBack: "ಮತ್ತೆ ಸ್ವಾಗತ",
    signInDescription: "ನಿಮ್ಮ ಸಂಭಾಷಣೆಗಳನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.",
    emailAddress: "ಇಮೇಲ್ ವಿಳಾಸ",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    forgotPassword: "ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?",
    signingIn: "ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ",
    or: "ಅಥವಾ",
    continueWithGoogle: "Google ಮೂಲಕ ಮುಂದುವರಿಸಿ",
    continueWithGithub: "GitHub ಮೂಲಕ ಮುಂದುವರಿಸಿ",
    newHere: "ಹೊಸವರೇ?",
    homeHeroTitle: "ಕೇಂದ್ರೀಕೃತ AI ಸಂಭಾಷಣೆಗಳಿಗೆ ಸ್ವಚ್ಛ workspace.",
    homeHeroDescription: "ಚಾಟ್‌ಗಳನ್ನು ಬೇಗ ಪ್ರಾರಂಭಿಸಿ, Gemini ಮತ್ತು LLaMA ಮಾದರಿಗಳನ್ನು ಬದಲಿಸಿ, ನಿಮ್ಮ ಸಂಭಾಷಣೆ ಇತಿಹಾಸವನ್ನು ಒಂದು responsive interface ನಲ್ಲಿ ವ್ಯವಸ್ಥಿತವಾಗಿಡಿ.",
    homeFeatureSecureTitle: "ಸುರಕ್ಷಿತ ಸೆಷನ್‌ಗಳು",
    homeFeatureSecureDescription: "ನಿಮ್ಮ ಚಾಟ್‌ಗಳು ನಿಮ್ಮ ಖಾತೆಗೆ ಸಂಪರ್ಕಿತವಾಗಿರುತ್ತವೆ.",
    homeFeatureModelTitle: "ಮಾದರಿ ಆಯ್ಕೆ",
    homeFeatureModelDescription: "ಒಂದು ಸ್ವಚ್ಛ composer ನಿಂದ Gemini ಅಥವಾ LLaMA ಬಳಸಿ.",
    homeFeatureSavedTitle: "ಉಳಿಸಿದ ಥ್ರೆಡ್‌ಗಳು",
    homeFeatureSavedDescription: "ಸಂಭಾಷಣೆಗಳನ್ನು ಹುಡುಕಿ, ಮರುಹೆಸರಿಸಿ, ಆರ್ಕೈವ್ ಮಾಡಿ, ಮತ್ತೆ ತೆರೆಯಿರಿ.",
  },
  te: {
    accountAndPreferences: "ఖాతా మరియు అభిరుచులు",
    accountDetails: "ఖాతా వివరాలు",
    analyzeData: "డేటా విశ్లేషించు",
    analyzeImage: "చిత్రం విశ్లేషించు",
    archive: "ఆర్కైవ్",
    archived: "ఆర్కైవ్",
    attach: "జతచేయి",
    brainstorm: "ఆలోచనలు",
    camera: "కెమెరా",
    closeProfile: "ప్రొఫైల్ మూసివేయి",
    copied: "కాపీ అయింది",
    copy: "కాపీ",
    current: "ప్రస్తుతం",
    dark: "డార్క్",
    delete: "తొలగించు",
    document: "డాక్యుమెంట్",
    email: "ఇమెయిల్",
    emailUpdated: "ఇమెయిల్ అప్డేట్ అయింది.",
    generateIdeas: "ఆలోచనలు రూపొందించు",
    generateImages: "చిత్రాలు రూపొందించు",
    helpMeWrite: "రాయడంలో సహాయం",
    improveWriting: "రచన మెరుగుపరచు",
    language: "భాష",
    learnAbout: "తెలుసుకోండి",
    light: "లైట్",
    logout: "లాగౌట్",
    messagePlaceholder: "RVK కు సందేశం పంపండి",
    myProfile: "నా ప్రొఫైల్",
    name: "పేరు",
    nameUpdated: "పేరు అప్డేట్ అయింది.",
    newChat: "కొత్త చాట్",
    preferences: "అభిరుచులు",
    preferencesDescription: "మీ వర్క్‌స్పేస్ కోసం ఇంటర్‌ఫేస్ మార్చండి.",
    profileDescription: "మీ పేరు మరియు సైన్-ఇన్ ఇమెయిల్ అప్డేట్‌గా ఉంచండి.",
    photos: "ఫోటోలు",
    recents: "ఇటీవలి",
    rename: "పేరు మార్చు",
    searchChats: "చాట్ వెతుకు",
    seeLess: "తక్కువ చూపు",
    seeMore: "ఇంకా చూడండి",
    sendMessage: "సందేశం పంపు",
    startVoiceInput: "వాయిస్ ఇన్పుట్ ప్రారంభించు",
    stopVoiceInput: "వాయిస్ ఇన్పుట్ ఆపు",
    summarizeText: "సారాంశం",
    switchToDark: "డార్క్ మోడ్",
    switchToLight: "లైట్ మోడ్",
    theme: "థీమ్",
    translate: "అనువదించు",
    unarchive: "ఆర్కైవ్ తీసివేయి",
    unpin: "అన్పిన్",
    update: "అప్డేట్",
    updating: "అప్డేట్ అవుతోంది",
    user: "యూజర్",
    voiceUnsupported: "వాయిస్ ఇన్పుట్ సపోర్ట్ లేదు",
    listeningMessage: "వింటోంది... సహజంగా మాట్లాడండి, ఆపడానికి మైక్ నొక్కండి.",
    welcomeDescription: "ఏదైనా అడగండి, ఫైల్ జతచేయండి, లేదా సేవ్ చేసిన చాట్ కొనసాగించండి.",
    welcomeTitle: "మనం ఏం పని చేద్దాం?",
    signIn: "సైన్ ఇన్",
    start: "ప్రారంభించండి",
    createAccount: "ఖాతా సృష్టించండి",
    welcomeBack: "మళ్లీ స్వాగతం",
    signInDescription: "మీ సంభాషణలను కొనసాగించడానికి సైన్ ఇన్ చేయండి.",
    emailAddress: "ఇమెయిల్ చిరునామా",
    password: "పాస్‌వర్డ్",
    forgotPassword: "పాస్‌వర్డ్ మర్చిపోయారా?",
    signingIn: "సైన్ ఇన్ అవుతోంది",
    or: "లేదా",
    continueWithGoogle: "Google తో కొనసాగించండి",
    continueWithGithub: "GitHub తో కొనసాగించండి",
    newHere: "ఇక్కడ కొత్తవారా?",
    homeHeroTitle: "కేంద్రీకృత AI సంభాషణల కోసం శుభ్రమైన workspace.",
    homeHeroDescription: "త్వరగా చాట్‌లు ప్రారంభించండి, Gemini మరియు LLaMA మోడళ్ల మధ్య మారండి, మీ సంభాషణ చరిత్రను ఒక responsive interface లో నిర్వహించండి.",
    homeFeatureSecureTitle: "సురక్షిత సెషన్‌లు",
    homeFeatureSecureDescription: "మీ చాట్‌లు మీ ఖాతాతో అనుసంధానంగా ఉంటాయి.",
    homeFeatureModelTitle: "మోడల్ ఎంపిక",
    homeFeatureModelDescription: "ఒక శుభ్రమైన composer నుండి Gemini లేదా LLaMA ఉపయోగించండి.",
    homeFeatureSavedTitle: "సేవ్ చేసిన థ్రెడ్‌లు",
    homeFeatureSavedDescription: "సంభాషణలను వెతకండి, పేరు మార్చండి, ఆర్కైవ్ చేయండి, మళ్లీ తెరవండి.",
  },
  ta: {
    accountAndPreferences: "கணக்கு மற்றும் விருப்பங்கள்",
    accountDetails: "கணக்கு விவரங்கள்",
    analyzeData: "தரவு பகுப்பாய்வு",
    analyzeImage: "படம் பகுப்பாய்வு",
    archive: "காப்பகம்",
    archived: "காப்பகம்",
    attach: "இணை",
    brainstorm: "யோசனைகள்",
    camera: "கேமரா",
    closeProfile: "சுயவிவரத்தை மூடு",
    copied: "நகலெடுக்கப்பட்டது",
    copy: "நகலெடு",
    current: "தற்போது",
    dark: "டார்க்",
    delete: "அழி",
    document: "ஆவணம்",
    email: "மின்னஞ்சல்",
    emailUpdated: "மின்னஞ்சல் புதுப்பிக்கப்பட்டது.",
    generateIdeas: "யோசனைகள் உருவாக்கு",
    generateImages: "படங்கள் உருவாக்கு",
    helpMeWrite: "எழுத உதவி",
    improveWriting: "எழுத்தை மேம்படுத்து",
    language: "மொழி",
    learnAbout: "அறிந்து கொள்",
    light: "லைட்",
    logout: "வெளியேறு",
    messagePlaceholder: "RVK-க்கு செய்தி அனுப்பு",
    myProfile: "என் சுயவிவரம்",
    name: "பெயர்",
    nameUpdated: "பெயர் புதுப்பிக்கப்பட்டது.",
    newChat: "புதிய உரையாடல்",
    preferences: "விருப்பங்கள்",
    preferencesDescription: "உங்கள் வேலைப்பரப்பிற்கான இடைமுகத்தை மாற்றவும்.",
    profileDescription: "உங்கள் பெயர் மற்றும் மின்னஞ்சலை புதுப்பித்து வைத்திருங்கள்.",
    photos: "புகைப்படங்கள்",
    recents: "சமீபத்தியவை",
    rename: "பெயர் மாற்று",
    searchChats: "உரையாடல் தேடு",
    seeLess: "குறைவாக காட்டு",
    seeMore: "மேலும் காட்டு",
    sendMessage: "செய்தி அனுப்பு",
    startVoiceInput: "குரல் உள்ளீடு தொடங்கு",
    stopVoiceInput: "குரல் உள்ளீடு நிறுத்து",
    summarizeText: "சுருக்கம்",
    switchToDark: "டார்க் மோடு",
    switchToLight: "லைட் மோடு",
    theme: "தீம்",
    translate: "மொழிபெயர்",
    unarchive: "காப்பகத்திலிருந்து நீக்கு",
    unpin: "அன்பின்",
    update: "புதுப்பி",
    updating: "புதுப்பிக்கிறது",
    user: "பயனர்",
    voiceUnsupported: "குரல் உள்ளீடு ஆதரிக்கப்படவில்லை",
    listeningMessage: "கேட்கிறது... இயல்பாக பேசுங்கள், பிறகு நிறுத்த மைக் அழுத்துங்கள்.",
    welcomeDescription: "ஏதாவது கேளுங்கள், கோப்புகளை இணைக்கவும், அல்லது சேமித்த உரையாடலை தொடரவும்.",
    welcomeTitle: "நாம் என்ன வேலை செய்வோம்?",
    signIn: "உள்நுழை",
    start: "தொடங்கு",
    createAccount: "கணக்கை உருவாக்கு",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    signInDescription: "உங்கள் உரையாடல்களைத் தொடர உள்நுழையுங்கள்.",
    emailAddress: "மின்னஞ்சல் முகவரி",
    password: "கடவுச்சொல்",
    forgotPassword: "கடவுச்சொல் மறந்துவிட்டதா?",
    signingIn: "உள்நுழைகிறது",
    or: "அல்லது",
    continueWithGoogle: "Google மூலம் தொடரவும்",
    continueWithGithub: "GitHub மூலம் தொடரவும்",
    newHere: "இங்கு புதியவரா?",
    homeHeroTitle: "கவனமான AI உரையாடல்களுக்கு சுத்தமான workspace.",
    homeHeroDescription: "விரைவாக அரட்டைகளைத் தொடங்குங்கள், Gemini மற்றும் LLaMA மாதிரிகளுக்கு இடையில் மாறுங்கள், உங்கள் உரையாடல் வரலாற்றை ஒரு responsive interface இல் ஒழுங்குபடுத்துங்கள்.",
    homeFeatureSecureTitle: "பாதுகாப்பான அமர்வுகள்",
    homeFeatureSecureDescription: "உங்கள் அரட்டைகள் உங்கள் கணக்குடன் இணைந்தே இருக்கும்.",
    homeFeatureModelTitle: "மாதிரி தேர்வு",
    homeFeatureModelDescription: "ஒரு சுத்தமான composer இலிருந்து Gemini அல்லது LLaMA பயன்படுத்துங்கள்.",
    homeFeatureSavedTitle: "சேமித்த threads",
    homeFeatureSavedDescription: "உரையாடல்களைத் தேடுங்கள், பெயர் மாற்றுங்கள், archive செய்யுங்கள், மீண்டும் திறக்குங்கள்.",
  },
  ml: {
    accountAndPreferences: "അക്കൗണ്ടും മുൻഗണനകളും",
    accountDetails: "അക്കൗണ്ട് വിവരങ്ങൾ",
    analyzeData: "ഡാറ്റ വിശകലനം",
    analyzeImage: "ചിത്രം വിശകലനം",
    archive: "ആർക്കൈവ്",
    archived: "ആർക്കൈവ്",
    attach: "ചേർക്കുക",
    brainstorm: "ആശയങ്ങൾ",
    camera: "ക്യാമറ",
    closeProfile: "പ്രൊഫൈൽ അടയ്ക്കുക",
    copied: "പകർത്തി",
    copy: "പകർത്തുക",
    current: "നിലവിൽ",
    dark: "ഡാർക്ക്",
    delete: "ഇല്ലാതാക്കുക",
    document: "ഡോക്യുമെന്റ്",
    email: "ഇമെയിൽ",
    emailUpdated: "ഇമെയിൽ അപ്ഡേറ്റ് ചെയ്തു.",
    generateIdeas: "ആശയങ്ങൾ സൃഷ്ടിക്കുക",
    generateImages: "ചിത്രങ്ങൾ സൃഷ്ടിക്കുക",
    helpMeWrite: "എഴുതാൻ സഹായിക്കുക",
    improveWriting: "എഴുത്ത് മെച്ചപ്പെടുത്തുക",
    language: "ഭാഷ",
    learnAbout: "അറിയുക",
    light: "ലൈറ്റ്",
    logout: "ലോഗൗട്ട്",
    messagePlaceholder: "RVK-ന് സന്ദേശം അയയ്ക്കുക",
    myProfile: "എന്റെ പ്രൊഫൈൽ",
    name: "പേര്",
    nameUpdated: "പേര് അപ്ഡേറ്റ് ചെയ്തു.",
    newChat: "പുതിയ ചാറ്റ്",
    preferences: "മുൻഗണനകൾ",
    preferencesDescription: "നിങ്ങളുടെ വർക്ക്‌സ്‌പേസിനായി ഇന്റർഫേസ് ക്രമീകരിക്കുക.",
    profileDescription: "നിങ്ങളുടെ പേരും സൈൻ-ഇൻ ഇമെയിലും പുതുക്കി സൂക്ഷിക്കുക.",
    photos: "ഫോട്ടോകൾ",
    recents: "സമീപകാലം",
    rename: "പേര് മാറ്റുക",
    searchChats: "ചാറ്റുകൾ തിരയുക",
    seeLess: "കുറച്ച് കാണിക്കുക",
    seeMore: "കൂടുതൽ കാണിക്കുക",
    sendMessage: "സന്ദേശം അയയ്ക്കുക",
    startVoiceInput: "വോയ്സ് ഇൻപുട്ട് തുടങ്ങുക",
    stopVoiceInput: "വോയ്സ് ഇൻപുട്ട് നിർത്തുക",
    summarizeText: "സംഗ്രഹിക്കുക",
    switchToDark: "ഡാർക്ക് മോഡ്",
    switchToLight: "ലൈറ്റ് മോഡ്",
    theme: "തീം",
    translate: "വിവർത്തനം",
    unarchive: "ആർക്കൈവിൽ നിന്ന് മാറ്റുക",
    unpin: "അൺപിൻ",
    update: "അപ്ഡേറ്റ്",
    updating: "അപ്ഡേറ്റ് ചെയ്യുന്നു",
    user: "ഉപയോക്താവ്",
    voiceUnsupported: "വോയ്സ് ഇൻപുട്ട് പിന്തുണയ്ക്കുന്നില്ല",
    listeningMessage: "കേൾക്കുന്നു... സ്വാഭാവികമായി സംസാരിക്കുക, നിർത്താൻ മൈക്ക് അമർത്തുക.",
    welcomeDescription: "എന്തും ചോദിക്കുക, ഫയലുകൾ ചേർക്കുക, അല്ലെങ്കിൽ സംരക്ഷിച്ച ചാറ്റ് തുടരുക.",
    welcomeTitle: "നാം എന്താണ് ചെയ്യുന്നത്?",
    signIn: "സൈൻ ഇൻ",
    start: "ആരംഭിക്കുക",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    welcomeBack: "വീണ്ടും സ്വാഗതം",
    signInDescription: "നിങ്ങളുടെ സംഭാഷണങ്ങൾ തുടരാൻ സൈൻ ഇൻ ചെയ്യുക.",
    emailAddress: "ഇമെയിൽ വിലാസം",
    password: "പാസ്‌വേഡ്",
    forgotPassword: "പാസ്‌വേഡ് മറന്നോ?",
    signingIn: "സൈൻ ഇൻ ചെയ്യുന്നു",
    or: "അല്ലെങ്കിൽ",
    continueWithGoogle: "Google ഉപയോഗിച്ച് തുടരുക",
    continueWithGithub: "GitHub ഉപയോഗിച്ച് തുടരുക",
    newHere: "ഇവിടെ പുതിയവരാണോ?",
    homeHeroTitle: "കേന്ദ്രീകൃത AI സംഭാഷണങ്ങൾക്ക് വൃത്തിയുള്ള workspace.",
    homeHeroDescription: "ചാറ്റുകൾ വേഗത്തിൽ ആരംഭിക്കുക, Gemini, LLaMA മോഡലുകൾ മാറുക, നിങ്ങളുടെ സംഭാഷണ ചരിത്രം ഒരു responsive interface ൽ ക്രമീകരിക്കുക.",
    homeFeatureSecureTitle: "സുരക്ഷിത സെഷനുകൾ",
    homeFeatureSecureDescription: "നിങ്ങളുടെ ചാറ്റുകൾ നിങ്ങളുടെ അക്കൗണ്ടുമായി ബന്ധിപ്പിച്ചുതന്നെയിരിക്കും.",
    homeFeatureModelTitle: "മോഡൽ തിരഞ്ഞെടുപ്പ്",
    homeFeatureModelDescription: "ഒരു വൃത്തിയുള്ള composer ൽ നിന്ന് Gemini അല്ലെങ്കിൽ LLaMA ഉപയോഗിക്കുക.",
    homeFeatureSavedTitle: "സേവ് ചെയ്ത threads",
    homeFeatureSavedDescription: "സംഭാഷണങ്ങൾ കണ്ടെത്തുക, പേര് മാറ്റുക, archive ചെയ്യുക, വീണ്ടും തുറക്കുക.",
  },
};

export function translate(language: AppLanguage, key: TranslationKey) {
  return localTranslations[language][key] || localTranslations.en[key];
}

function hasLocalTranslation(language: AppLanguage, key: TranslationKey) {
  return Boolean(localTranslations[language][key]);
}

export function useAppTranslation() {
  const language = useLanguage();
  const { t: tolgeeTranslate } = useTranslate(undefined, { useSuspense: false });

  return (key: TranslationKey) => {
    const localValue = translate(language, key);

    if (language !== "en" && hasLocalTranslation(language, key)) {
      return localValue;
    }

    return tolgeeTranslate(key, localValue);
  };
}
